# Parâmetros base da otimização
max_gen = 35  # Número máximo de gerações
pop_len = 100  # Tamanho da população
x_len = 2  # Número de genes em cada indivíduo (x)
elitism_rate = 0.2  # Percentual de indivíduos na população atual que serão mantidos na população seguinte
mutation_rate = 0.1  # Probabilidade de um determinado indivíduo sofrer mutação
#random_seed = 0  # Semente para geração dos números aleatórios. Caso não seja definida, assumirá o valor de time.time()

# Métodos a serem empregados nas operações executadas pelo AG (operadores genéticos)
select_method = 'roulette'  # Método de seleção a ser empregado
cross_method = 'arithmetic_recombination'  # Método empregado na recombinação (crossover)
mut_method = 'nonuniform_gaussian'  # Método empregado na mutação
gene_type = 'real'  # Tipo numérico dos genes do indivíduo (dita como a primeira população será inicializada)

# Parâmetros associados às restrições
x_l = [0.0, 0.0]  # Limites inferiores para cada um dos genes do indivíduo
x_u = [1.0, 1.0]  # Limites superiores para cada um dos genes do indivíduo
restrictions_weight = 1000  # Peso que determina o impacto do desrespeito das restrições na função objetivo

# Parâmetros associados às condições de parada
#max_exec_time_seconds = 3600  # Duração máxima da execução

## Se a variação da função objetivo (levando-se em conta o melhor indivíduo) for menor do que "min_f_obj_value_diff"
## por "generations_to_check_f_obj_diff" gerações, a otimização será encerrada
#min_f_obj_value_diff = 1e-6
#generations_to_check_f_obj_diff = 15

# Parâmetros associados à apresentação dos resultados
plot_f_obj_history = true  # Define se a evolução da função objetivo será representada graficamente
log_level = 'debug'  # Nível dos logs apresentados ("debug", "info", "error" ou None)
log_path = 'finance.log'  # Nome do arquivo onde os logs serão armazenados

# Parâmetros associados à recombinação. Os parâmetros a serem definidos podem variar de acordo com o método escolhido
[crossover]
alpha = 0.3  # Fator que define o peso que cada pai terá na computação de seus filhos (sugere-se 0 < alpha < 0.5)

# Parâmetros associados à mutação. Os parâmetros a serem definidos podem variar de acordo com o método escolhido
[mutation]
reduce_mut_factor = 6  # Quanto maior for o "reduce_mut_factor", mais sutil será a alteração provocada pela mutação